donations:
  spreadsheetURL: https://docs.google.com/spreadsheets/d/e/2PACX-1vTXKpZ8iB5Nz6mHl5iYUAA68DU1D-gCnwuDREnVULI9JrOnh1CF8U1RF6zDbVfrkw/pub?gid=1443797343&single=true&output=csv
  target: 100000
